config/routes.rb
Superpod::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :containers do
    collection do
      get :start
      get :stop
      post :remove
      post :commit
    end
  end

  resources :images do
    collection do
      post :launch
      post :remove
    end
  end

  resources :host_configs
  resources :welcome, :only => ['index']

  root :to => 'welcome#index'
  get :containers, :to => 'containers#index', :as => :user_root

  devise_for :users

end

app/models/host_config.rb
class HostConfig < ActiveRecord::Base
end

app/controllers/host_configs_controller.rb
class HostConfigsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_host_config, only: [:show, :edit, :update, :destroy]

  # GET /host_configs
  # GET /host_configs.json
  def index
    @host_configs = HostConfig.all
  end

  # GET /host_configs/1
  # GET /host_configs/1.json
  def show
  end

  # GET /host_configs/new
  def new
    @host_config = HostConfig.new
  end

  # GET /host_configs/1/edit
  def edit
  end

  # POST /host_configs
  # POST /host_configs.json
  def create
    @host_config = HostConfig.new(host_config_params)

    respond_to do |format|
      if @host_config.save
        format.html { redirect_to @host_config, notice: 'Host config was successfully created.' }
        format.json { render action: 'show', status: :created, location: @host_config }
      else
        format.html { render action: 'new' }
        format.json { render json: @host_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /host_configs/1
  # PATCH/PUT /host_configs/1.json
  def update
    respond_to do |format|
      if @host_config.update(host_config_params)
        format.html { redirect_to @host_config, notice: 'Host config was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @host_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /host_configs/1
  # DELETE /host_configs/1.json
  def destroy
    @host_config.destroy
    respond_to do |format|
      format.html { redirect_to host_configs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host_config
      @host_config = HostConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_config_params
      params.require(:host_config).permit(:host, :port)
    end
end

app/helpers/host_configs_helper.rb
module HostConfigsHelper
end

app/views/host_configs/_form.html.erb
<%= form_for(@host_config) do |f| %>
  <% if @host_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host_config.errors.count, "error") %> prohibited this host_config from being saved:</h2>

      <ul>
      <% @host_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.text_field :port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/host_configs/edit.html.erb
<h1>Editing host_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @host_config %> |
<%= link_to 'Back', host_configs_path %>

app/views/host_configs/index.html.erb
<h1>Listing host_configs</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Port</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @host_configs.each do |host_config| %>
      <tr>
        <td><%= host_config.host %></td>
        <td><%= host_config.port %></td>
        <td><%= link_to 'Show', host_config %></td>
        <td><%= link_to 'Edit', edit_host_config_path(host_config) %></td>
        <td><%= link_to 'Destroy', host_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host config', new_host_config_path %>

app/views/host_configs/new.html.erb
<h1>New host_config</h1>

<%= render 'form' %>

<%= link_to 'Back', host_configs_path %>

app/views/host_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @host_config.host %>
</p>

<p>
  <strong>Port:</strong>
  <%= @host_config.port %>
</p>

<%= link_to 'Edit', edit_host_config_path(@host_config) %> |
<%= link_to 'Back', host_configs_path %>