config/routes.rb
Superpod::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :containers do
    collection do
      get :start
      get :stop
      post :remove
      post :commit
    end
  end

  resources :images do
    collection do
      post :launch
      post :remove
    end
  end

  resources :host_configs
  resources :welcome, :only => ['index']

  root :to => 'welcome#index'
  get :containers, :to => 'containers#index', :as => :user_root

  devise_for :users

end

app/models/container.rb
require 'docker'
class Container < ActiveRecord::Base

  host_config = HostConfig.all[0]
  Docker.url = "http://#{host_config.host}:#{host_config.port}"

  def self.all_on_host author
    cons = Array.new
    Docker::Container.all(:all => true).each do |c|
      if author == nil || author == "all"
        cons << c
      elsif author == c.json["Name"].gsub(/\//, "").split('___')[1]
        cons << c
      end
    end
    cons
  end

  def self.get_free_port
    cons = Docker::Container.all(:all => true)
    using_ports = Array.new

    cons.each do |c|
      using_ports << c.json["HostConfig"]["PortBindings"]["8000/tcp"][0]["HostPort"].to_i
    end
    using_ports.sort!

    free = 8000
    (8001..9999).each do |i|
      if using_ports.include?(i) == false
        free = i
        break
      end
    end
    free
  end

  def self.start cid
    container = Docker::Container.get(cid)
    container.start
  end

  def self.stop cid
    container = Docker::Container.get(cid)
    container.stop
  end

  def self.remove cid
    container = Docker::Container.get(cid)
    container.delete(:force => true)
  end

  def self.commit_as_another cid, image_name, overwrite, author
    container = Docker::Container.get(cid)
    if overwrite
      image_name = container.json["Config"]["Image"].split(':')[0]
    end
    image_name = image_name + "___" + author
    url = "#{Docker.url}/commit?container=#{container.id}&repo=#{image_name}&tag=latest"
    RestClient.post(url, "{}", :content_type => :json, :accept => :json)
  end

  def self.get_state_word status
    state = Hash["en" => "stopped", "ja" => "停止中"]
    if status == "true"
      state = Hash["en" => "running", "ja" => "起動中"]
    end
    state
  end

  def self.get_state_color status
    color = "#FF7548"
    if status == "true"
      color = "#70D53C"
    end
    color
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containers
  # GET /containers.json
  def index
    author = params["author"]
    if author
      @selected_user = author
    else
      @selected_user = User.get_account(current_user.email)
    end
    @users = Array.new
    User.all.each do |u|
      @users << u.email[0..u.email.index('@')-1] 
    end
    @host = HostConfig.all[0].host
    @containers = Container.all_on_host(author)
  end

  def start
    author = params["author"]
    Container.start(params["cid"])
    redirect_to containers_path + "?author=" + author
  end

  def stop
    author = params["author"]
    Container.stop(params["cid"])
    redirect_to containers_path + "?author=" + author
  end

  def remove
    cid = params["cid"]
    Container.remove(cid)
    redirect_to containers_path
  end

  def commit
    cid = params["save_cid"]
    overwrite = params["overwrite"]
    image_name = params["image_name"]
    author = User.get_account(current_user.email)
    Container.commit_as_another(cid, image_name, overwrite, author)
    redirect_to images_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params[:container]
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_commit_modal.html.erb
<!-- Commit Modal Dialog -->
<div class="modal fade" id="commitModal" tabindex="-1" role="dialog" aria-labelledby="commitModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">保存</span></button>
        <h4 class="modal-title" id="exampleModalLabel"></h4>
      </div>
      <%= form_tag(commit_containers_path, :method => :post) do %> 
      <div class="modal-body">
        <div class="form-group">
          <label id="label-message" for="message-text" class="control-label"></label>
          <%= text_field_tag :image_name, "", :class => "form-control" %>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag :overwrite, true, false, {:onclick => "switch_checkbox()"} %>上書き
          </label>
        </div>
        <%= hidden_field_tag :save_cid %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        <%= submit_tag "保　存", :class => "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
<!--
$('#commitModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var param = button.data('whatever').split('|')
  var cname = param[0]
  var cid = param[1]
  var image = param[2]
  $('#save_cid').val(cid);
  var modal = $(this)
  modal.find('.modal-title').text("コンテナ " + "' " + cname + " '" + " をイメージとして保存");
  $("#label-message").html("イメージ名（元イメージ名：" + image + "）");
  setTimeout(function() {$('#image_name').focus();}, 1000);
})

function switch_checkbox() {
  var val = $("#overwrite:checked").val();
  if(val == "true") {
    $('#image_name').attr('readonly', true);
  } else {
    $('#image_name').attr('readonly', false);
  }
}
// -->
</script>

app/views/containers/_remove_modal.html.erb
<!-- Remove Modal Dialog -->
<div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="removeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title" id="exampleModalLabel">コンテナ削除</h2>
      </div>

      <%= form_tag(remove_containers_path, :method => :post) do %> 
        <%= hidden_field_tag :cid %>
        <div class="modal-body">
          <h3>Are you sure?</h3>
          <h4 id="remove_target"></h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Remove", :class => "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
<!--
$('#removeModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var param = button.data('whatever').split('|')
  var cname = param[0]
  var cauthor = param[1]
  var cid = param[2]
  var title = cname + "   ( " + cauthor + " )";
  $('#remove_target').html(title);
  $('#cid').val(cid);
  var modal = $(this)
  modal.find('.modal-title').text("Remove Container")
})
// -->
</script>

app/views/containers/_ssh_modal.html.erb
<!-- SSH Modal Dialog -->
<div class="modal fade" id="sshModal" tabindex="-1" role="dialog" aria-labelledby="sshModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title" id="exampleModalLabel">コンテナに接続</h2>
      </div>
      <div class="modal-body">
        <h4>以下のコマンドを実行</h4>
        <input type="text" id="container_name" value="" readonly="readonly" onclick="copy2clipbord();" style="width:80%;">
        <br/>
        <br/>
        <h5>dockerクライアントを入れていない場合、以下の手順でセットアップしてください。</h5>
        <h5>1. Boot2dokerをインストール (<a href="http://boot2docker.io/" target="_blank">公式サイト</a>を参照)</h5>
        <h5>2. Boot2dokerを起動後 'docker pull tokumura/docker-client-v13' を実行</h5>
        <h5>3. Boot2doker上で 'docker run -i -t tokumura/docker-client-v13 /bin/bash' を実行</h5>
        <h5>4. Boot2doker上で 'export DOCKER_HOST=tcp://54.65.122.251:5422' を実行</h5>
        <h5>5. 上記コマンドで起動/ログインしたコンテナ内で 'docker version' を実行</h5>
        <h5>6. バージョン情報が表示されたら準備完了です。<br/>　'docker exec'を実行してコンテナにログインしてください。</h5>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
<!--
$('#sshModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var name = button.data('whatever')
  $('#container_name').val("docker exec -it " + name + " bash");
  var modal = $(this)
  modal.find('.modal-title').text("コンテナに接続")
})

function copy2clipbord() {
  $('#container_name').select();
}
// -->
</script>

app/views/containers/index.html.erb
<div style="margin-bottom:10px;">
  <h4 style="display:inline; margin-right:30px;">コンテナ一覧</h4>
  <select id="userlist" class="form-control" 
   style="width:150px; display: inline;" onchange="narrow_down()">
    <option value="all">全て</option>
    <% @users.each do |u| %>
      <% selected = "" %>
      <% selected = "selected" if @selected_user == u %>
      <option <%=selected%>><%=u%></option>
    <% end %>
  </select>
</div>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>コンテナ名 ( 元イメージ )</th>
      <th>ORCAポート番号</th>
      <th>オーナー</th>
      <th>ステータス</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |con| %>
      <% image = con.json["Config"]["Image"].split(':')[0].split('___')[0] %>
      <% cname = con.json["Name"].gsub(/\//, "").split('___')[0] %>
      <% author = con.json["Name"].gsub(/\//, "").split('___')[1] %>
      <% state = Container.get_state_word(con.json["State"]["Running"].to_s) %>
      <% color = Container.get_state_color(con.json["State"]["Running"].to_s) %>
      <tr>
        <td><%= con.id[0..11] %></td>
        <td>
          <b><%= cname %></b>  ( <%=image%> )
        </td>
        <td><%= con.json["HostConfig"]["PortBindings"]["8000/tcp"][0]["HostPort"] %></td>
        <td><%= author %></td>
        <td><i class="fa fa-circle" style="color:<%=color%>}"></i> <%= state["ja"] %></td>
        <td>
          <% if state["en"] == "running" %>
            <%= link_to '停止', stop_containers_path + "?cid=#{con.id}&author=#{@selected_user}", 
                :class => 'btn btn-warning btn-xs', :style => 'width:70px;' %>
          <% else %>
            <%= link_to '起動', start_containers_path + "?cid=#{con.id}&author=#{@selected_user}", 
                :class => 'btn btn-info btn-xs', :style => 'width:70px;' %>
          <% end %>
        </td>
        <td>
          <button type="button" class="btn btn-danger btn-xs" style="width:70px;" data-toggle="modal" 
            data-target="#removeModal" data-whatever="<%= cname + '|' + author + '|' + con.id %>">削除</button>
        </td>
        <td>
          <button type="button" class="btn btn-primary btn-xs" style="width:70px;" data-toggle="modal" 
            data-target="#commitModal" data-whatever="<%= cname + '|' + con.id + "|" + image %>">保存</button>
        </td>
        <td>
          <button type="button" class="btn btn-default btn-xs" style="width:70px;" data-toggle="modal" 
            data-target="#sshModal" data-whatever="<%= cname %>">SSH</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'remove_modal' %>
<%= render 'ssh_modal' %>
<%= render 'commit_modal' %>

<script type="text/javascript">
<!--
  function narrow_down() {
    var user = $("#userlist").val();
    window.location.href = "<%=containers_path%>?author=" + user;
  }
// -->
</script>