config/routes.rb
Superpod::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :containers do
    collection do
      get :start
      get :stop
      post :remove
      post :commit
    end
  end

  resources :images do
    collection do
      post :launch
      post :remove
    end
  end

  resources :host_configs
  resources :welcome, :only => ['index']

  root :to => 'welcome#index'
  get :containers, :to => 'containers#index', :as => :user_root

  devise_for :users

end

app/models/image.rb
require 'docker'
class Image < ActiveRecord::Base

  host_config = HostConfig.all[0]
  Docker.url = "http://#{host_config.host}:#{host_config.port}"
  
  def self.all_on_host author
    images = Array.new
    Docker::Image.all.each do |img|
      if author == nil || author == "all"
        images << img
      elsif author == img.info["RepoTags"].to_s.gsub(/\"|\[|\]/, "").split('___')[1].split(':')[0]
        images << img 
      end
    end
    images
  end

  def self.launch image, name
    orca_port = Container.get_free_port
    container = Docker::Container.create('name' => name, 'Image' => image, 
                                         'ExposedPorts' => '8000/tcp', 
                                         'OpenStdin' => true,
                                         'Tty' => true)
    container.stop
    req_json = '{"PortBindings":{ "8000/tcp": [{ "HostPort": "orca_port" }] }}'.gsub(/orca_port/, "#{orca_port}")
    RestClient.post Docker.url + "/containers/#{container.id}/start?name=#{name}", req_json, :content_type => :json, :accept => :json
    #Container.save(container.id.to_s[0..11], author)
  end

  def self.remove imgid
    image = Docker::Image.get(imgid)
    image.remove(:force => true)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    author = params["author"]
    if author
      @selected_user = author
    else
      @selected_user = User.get_account(current_user.email)
      author = @selected_user
    end
    @users = Array.new
    User.all.each do |u|
      @users << u.email[0..u.email.index('@')-1] 
    end
    @images = Image.all_on_host(author)
  end

  def launch
    image = params["image_name"]
    author = current_user.email[0..current_user.email.index('@')-1]
    container_name = params["container_name"] + "___" + author
    Image.launch(image, container_name)
    redirect_to containers_path + "?author=" + author
  end

  def remove
    imgid = params["image_id"]
    author = params["author"]
    Image.remove(imgid)
    redirect_to images_path + "?author=#{author}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params[:image]
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_launch_modal.html.erb
<!-- Launch Modal Dialog -->
<div class="modal fade" id="launchModal" tabindex="-1" role="dialog" aria-labelledby="launchModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Launch</h4>
      </div>
      <%= form_tag(launch_images_path, :method => :post) do %> 
      <div class="modal-body">
          <div class="form-group">
            <label for="message-text" class="control-label">Container Name</label>
            <%= text_field_tag :container_name, "", :class => "form-control" %>
          </div>
          <%= hidden_field_tag :image_name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Launch", :class => "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
<!--
$('#launchModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var param = button.data('whatever').split('|')
  var image_full = param[0];
  var image_name = param[0].split('___')[0];
  var image_id = param[1]
  var title = image_name + "  ( " + image_id.substring(0, 10) + " )";
  $('#image_name').val(image_full);
  var modal = $(this)
  modal.find('.modal-title').text(title)
  setTimeout(function() {$('#container_name').focus();}, 1000);
})
// -->
</script>

app/views/images/_remove_modal.html.erb
<!-- Remove Modal Dialog -->
<div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="removeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title" id="exampleModalLabel">Remove Image</h2>
      </div>
      <%= form_tag(remove_images_path, :method => :post) do %> 
        <%= hidden_field_tag :author %>
        <%= hidden_field_tag :image_id %>
        <div class="modal-body">
          <h3>Are you sure?</h3>
          <h4 id="remove_target"></h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Remove", :class => "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
<!--
$('#removeModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var param = button.data('whatever').split('|')
  var image_full = param[0]
  var image_name = param[0].split('___')[0]
  var image_id = param[1]
  var title = image_name + "  ( " + image_id.substring(0, 10) + " )";
  $('#remove_target').html(title);
  $('#image_id').val(image_id);
  $('#author').val('<%=author%>');
  var modal = $(this)
  modal.find('.modal-title').text("Remove Image")
})
// -->
</script>

app/views/images/index.html.erb
<div style="margin-bottom:10px;">
  <h4 style="display:inline; margin-right:30px;">イメージ一覧</h4>
  <select id="userlist" class="form-control" 
   style="width:150px; display: inline;" onchange="narrow_down()">
    <option value="all">全て</option>
    <% @users.each do |u| %>
      <% selected = "" %>
      <% selected = "selected" if @selected_user == u %>
      <option <%=selected%>><%=u%></option>
    <% end %>
  </select>
</div>

<table class="table table-hover table-bordered" style="width:70%;">
  <thead>
    <tr>
      <th>ID</th>
      <th>イメージ名</th>
      <th>作成者</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |img| %>
      <% img_full = img.info["RepoTags"].to_s.gsub(/\"|\[|\]/, "") %>
      <% img_tag = img_full.split(':')[1] %>
      <% img_name  = img_full.split(':')[0].split('___')[0] %>
      <% author = img_full.split(':')[0].split('___')[1] %>
      <% img_id = img.id %>
      <tr>
        <td><%= img_id[0..10] %></td>
        <td><%= img_name %></td>
        <td><%= author %></td>
        <td>
          <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#launchModal" 
           data-whatever="<%= img_full + "|" + img_id %>">Launch</button>
        </td>
        <td>
          <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#removeModal" 
           data-whatever="<%= img_full + "|" + img_id %>">Remove</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'launch_modal' %>
<%= render partial: 'remove_modal', locals: {author: @selected_user} %>

<script type="text/javascript">
<!--
  function narrow_down() {
    var user = $("#userlist").val();
    window.location.href = "<%=images_path%>?author=" + user;
  }
// -->
</script>