config/routes.rb
Superpod::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :containers do
    collection do
      get :start
      get :stop
      post :remove
      post :commit
    end
  end

  resources :images do
    collection do
      post :launch
      post :remove
    end
  end

  resources :host_configs
  resources :welcome, :only => ['index']

  root :to => 'welcome#index'
  get :containers, :to => 'containers#index', :as => :user_root

  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superpod</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%
  active_status_image = ""
  active_status_container = ""

  if request.path_info.index("/containers") != nil
    active_status_container = "active"
  elsif request.path_info.index("/images") != nil
    active_status_image = "active"
  end
%>

<% if current_user %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= containers_path %>">Superpod</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%=active_status_container%>"><a href="<%= containers_path %>">コンテナ<span class="sr-only">(current)</span></a></li>
        <li class="<%=active_status_image%>"><a href="<%= images_path %>">イメージ</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <%= current_user.email[0..current_user.email.index('@')-1] %>
        <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">アカウント</a></li>
            <li><a href="#">お問い合わせ</a></li>
            <% if current_user.email.index('t-okumura@') %>
              <li><a href="<%= rails_admin_path %>">RailsAdmin</a></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

<div class="container-fluid">
  <% if alert && request.path_info.index("/users/sign_in") != nil  %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>

</body>
</html>